blank_issues_enabled: true
contact_links:
  - name: "â” Start a Discussion"
    about: Ask a general question or start a discussion
    url: https://github.com/smashedr/typescript-action/discussions/new?category=q-a

  - name: "ğŸ’¬ Join Discord"
    about: Chat with us about anything
    url: https://discord.gg/wXy6m2X8wY

  - name: "ğŸ“ View Documentation"
    about: Review the documentation
    url: https://cssnr.github.io/brew-python-resources/
